name: lcms_net
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scikit-learn=1.5.1=py312h526ad5a_0
  - imbalanced-learn=0.12.3=py312h06a4308_1
  - matplotlib
  - pip:
       - scikit-optimize==0.10.2  
       - pyopenms==3.2
       - tensorflow==2.18.1
       - keras-tuner==1.4.7
       - keras==3.6.0
       - openpyxl